### ISSUE TITLE
Density FPN

### ISSUE THREAD

**Issue by Fly-dream12** [we1pingyu/DSHNet#3]
Thanks for your code. I found in most config files, there exists "DensityFPN", however, i can not find the corresponding implementations. Can you add these files ?

**Comment by we1pingyu** [comment]
It's just something experimental, and it dose not work so we comment those code in config. Please do not care.

**Comment by Fly-dream12** [comment]
By the way, i wonder how to choose the head class and the tail  class.  I have done the experiments on my own dataset, however, after the sample method in your code, the results are even worse.

**Comment by we1pingyu** [comment]
This work is specifically designed for the datasets that contain many targets in a single image, such us UAV datasets. If your dateset is a general one, DSHNet cannot sample enough positive samples (eg. 128 in implementation of mmdet) for every head. Please refer to our paper for more details.
